[package]
name = "aoc4"
version = "0.1.0"
authors = ["Erik McClure <erikm@fundament.software>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"